name: Comment on PR
author: Aaron Klaassen <aaron@unsplash.com>
description: Leaves a comment on an open PR matching a push event.
branding:
  icon: 'message-square'  
  color: 'blue'
inputs:
  msg: 
    description: Comment's message
    required: false
  check_for_duplicate_msg:
    description: If false, action doesn't check for duplicate message.
    required: false
    default: true
  delete_prev_regex_msg:
    description: If provided, all messages matching the given regex will be deleted.
    required: false
    default: ~
  duplicate_msg_pattern:
    description: If provided, the regex pattern will be used when checking for duplicate messages.
    required: false
    default: ~

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.msg }}
    - ${{ inputs.check_for_duplicate_msg }}
    - ${{ inputs.delete_prev_regex_msg }}
    - ${{ inputs.duplicate_msg_pattern }}

